eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
  instance:
    prefer-ip-address: true
    instance-id:
      ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
server:
  port: 8072
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true