server:
  port: 9002
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-zipkin-s2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    appname: service-zipkin-s2